# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1siG5t0CXxHK_Ntxq4h002zKvySL0CGZP
"""





"""print("hello")

"""

print("hello")
a=int(input())
b=int(input())
print(a+b)